In [3]:
import numpy as np


In [12]:
array_2d=np.arange(24)               #how to make matrix
array_2d.shape=(6,4)             
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
array_2d[:2,:2]

array([[0, 1],
       [4, 5]])

In [14]:
#broadcasting

In [15]:
array_1d=np.arange(10)

In [16]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
array_2d=np.ones((4,4))
array_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
array_2d[0]=200
array_2d

array([[200., 200., 200., 200.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [22]:
array_2d[1]=300
array_2d

array([[200., 200., 200., 200.],
       [300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [23]:
array_2d[2]=400
array_2d

array([[200., 200., 200., 200.],
       [300., 300., 300., 300.],
       [400., 400., 400., 400.],
       [  1.,   1.,   1.,   1.]])

In [24]:
array_2d[3]=500                      #there is called broadcasting
array_2d

array([[200., 200., 200., 200.],
       [300., 300., 300., 300.],
       [400., 400., 400., 400.],
       [500., 500., 500., 500.]])

In [26]:
array_2d + np.arange(0,4)

array([[200., 201., 202., 203.],
       [300., 301., 302., 303.],
       [400., 401., 402., 403.],
       [500., 501., 502., 503.]])

In [28]:
array_2d + 300

array([[500., 500., 500., 500.],
       [600., 600., 600., 600.],
       [700., 700., 700., 700.],
       [800., 800., 800., 800.]])

In [29]:
array_2d[[0,1]]

array([[200., 200., 200., 200.],
       [300., 300., 300., 300.]])

In [30]:
array_2d[0,1]

200.0

In [31]:
array_2d[:,[2]]

array([[200.],
       [300.],
       [400.],
       [500.]])

In [32]:
array_2d[[3,0,1]]

array([[500., 500., 500., 500.],
       [200., 200., 200., 200.],
       [300., 300., 300., 300.]])

In [4]:
import numpy as np

In [5]:
array_2d=np.arange(24)
array_2d.shape=(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
array_2d[[2,3]]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
array_2d[:,[2,3]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [16]:
array_1d=np.arange(1,11)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
array_1d < 3

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [18]:
array_1d>3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [19]:
array_1d%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [20]:
array_1d+3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [21]:
mod_2_mask_1d=array_1d%2==0          #importrant
mod_2_mask_1d

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [23]:
array_1d[mod_2_mask_1d]
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
array_1d=np.arange(7)
array_1d

array([0, 1, 2, 3, 4, 5, 6])

In [26]:
np.sqrt(array_1d)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974])

In [27]:
np.max(array_1d)

6

In [28]:
np.min(array_1d)

0

In [29]:
array_2d=np.arange(30).reshape(6,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [30]:
array_2d.sum()

435

In [31]:
array_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110, 135])

In [32]:
array_2d % 3 !=0

array([[False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True]])

In [33]:
mask_mod_3=0!=array_2d%3
mask_mod_3

array([[False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True]])